### PR TITLE
CP-1252 Release route.dart 0.8.1

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-1252

JIRA and PR's included in this release: 

 CP-1257  - Fix page title setting for all routing cases  - https://github.com/Workiva/route.dart/pull/9
 CP-1274  - update dart formatting, route.dart dart_style 0.2.3  - https://github.com/Workiva/route.dart/pull/11

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/route.dart/compare/0.8.0...CP-1252_release_0.8.1

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1
- [x] Dev +1's only needed for Release ticket, push build is failing due to a separate dependency change which is correct in pr

Ready for merge and tag.

**Pull request merged**
