### PR TITLE
CP-1185 Release route.dart 0.8.0

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-1185

JIRA and PR's included in this release: 

 CP-1210  - fix skipped async test failure  - https://github.com/Workiva/route.dart/pull/3
 CP-1219  - Enable TravisCI, route.dart  - https://github.com/Workiva/route.dart/pull/5
 CP-1217  - ALL THE TODOS, route.dart  - https://github.com/Workiva/route.dart/pull/4
 CP-1235  - Use first specified default route, but dont throw on multiples  - https://github.com/Workiva/route.dart/pull/6

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/route.dart/compare/0.7.0...CP-1185_release_0.8.0

### CODE REVIEW

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1
- [x] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
