### PR TITLE
CP-1219 Enable TravisCI, route.dart

### PR DESCRIPTION
**Pull request by trentgrover-wf**
## Issue
- enable TravisCI
- remove some build scripts that no longer apply to us
- add travisCI and codecov badges to README
## Changes

**Source:**
- none

**Tests:**
- none
## Areas of Regression
- none
## Testing
- see if it runs?
## Code Review

@maxwellpeterson-wf
@evanweible-wf
@dustinlessard-wf 
@jayudey-wf

### CODE REVIEW

**Comment by dustinlessard-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10
- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
  - passing travis build
- [ ] Unit test created/updated
- [x] All unit tests pass 

Merging into master.

**Pull request merged**
