### PR TITLE
CP-1235 Use first specified default route, but dont throw on multiples

### PR DESCRIPTION
**Pull request by trentgrover-wf**
## Issue
- builds on top of previous PR: https://github.com/Workiva/route.dart/pull/4
  - easier view of diff: https://github.com/Workiva/route.dart/compare/unitTests...Workiva:dupDefaults
- The existing implementation throws if more than 1 route at the same level of the route hierarchy is specified as the `defaultRoute`.  This throw is somewhat arbitrary because we can easily just ignore all but the first specified `defaultRoute` and log an appropriate warning.
- If we allow multiple modules to append routes directly to the same root router node, there are likely to be conflicts between `defaultRoute`s specified in each individual module.  If we just use the first specified `defaultRoute`, the code that registers each module's routes can control the final default via the desired order of application.
- NOTE - this modification has very no / low risk, but we'll likely recommend that devs 'namespace' the routes of their sub-modules by providing separate mounting nodes for them
## Changes

**Source:**
- instead of throwing when multiple default routes are specified, log a verbose warning and keep the first specified as the functional default

**Tests:**
- added tests to ensure that multiple defaultRoutes work as expected
## Areas of Regression
- none in use
## Testing
- tests pass travisCI
## Code Review

@maxwellpeterson-wf
@evanweible-wf
@dustinlessard-wf 
@jayudey-wf

### CODE REVIEW

**Comment by dustinlessard-wf** [comment]
`The command "pub run dart_dev test" exited with 1.`

**Comment by trentgrover-wf** [comment]
yeah, not sure why test command bails immediately, but all tests pass in the coverage step...will investigate...

**Comment by trentgrover-wf** [comment]
@dustinlessard-wf seems to be a periodic issue with TravisCI's install of Content Shell.  re-ran and it passed

**Comment by maxwellpeterson-wf** [comment]
nice, I like this approach.
+1

**Comment by dustinlessard-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
@jayudey-wf ready for merge (after #4 )

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10
- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
- [x] Unit test created/updated
  - passing tests within travis
- [x] All unit tests pass

Merging into master.

**Pull request merged**
