### PR TITLE
CP-1648 Release route.dart 0.10.0

### PR DESCRIPTION
**Pull request by jayudey-wf**
JIRA: https://jira.webfilings.com/browse/CP-1648

Releases that need to go out at the same time (if any): 

JIRA and PR's included in this release: 

 CP-1714  - Support replace option on gotoUrl method  - https://github.com/Workiva/route.dart/pull/20

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/route.dart/compare/0.9.1...CP-1648_release_0.10.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/route.dart/compare/0.9.1...0.10.0

### CODE REVIEW

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1
- [x] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
