### PR TITLE
CP-1210 fix skipped async test failure

### PR DESCRIPTION
**Pull request by trentgrover-wf**
## Issue
- 2 tests were skipped because they were failing for an, at the time, unknown async reason
- test mocks could be better consolidated
## Changes

**Source:**
- changes are confined to test files

**Tests:**
- unskip the 2 skipped tests by adding `e.preventDefault` in the mock click handler
- reorganize the mocks so they're consolidated
## Areas of Regression
- none
## Testing
- make sure tests pass smithy
## Code Review

@maxwellpeterson-wf
@evanweible-wf
@dustinlessard-wf 
@jayudey-wf

### CODE REVIEW

**Comment by evanweible-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
@jayudey-wf ready for merge

**Comment by jayudey-wf** [comment]
QA Resource Approval: +10
- [x] Testing instruction
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
  - tests pass locally
- [x] Unit test created/updated
- [x] All unit tests pass

Merging into master.

**Pull request merged**
