### PR TITLE
CP-1715 Release route.dart 0.10.1

### PR DESCRIPTION
**Pull request by rmconsole3-wf**
Pulls Included in Release:
- [CP-2673 Handle initial route being rejected by preEnter](https://github.com/Workiva/route.dart/pull/22)

Requested by: charliekump-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/route.dart/compare/0.10.0...version-bump-route-dart-0-10-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/route.dart/compare/0.10.0...0.10.1

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven

Number of Findings: 0

**Comment by rmconsole-wf** [comment]
@rmconsole3-wf, @edjackson+rmconsole-wf
* It looks like you have not included any tickets in the title of this PR, but this repo requires tickets for all pull requests. Please create a ticket for this change, or click <a href='https://w-rmconsole.appspot.com/api/v1/pulls/86351314/addTicketToTitle'>here</a> to have Rosie create one for you.

**Comment by sebastianmalysa-wf** [comment]
+1

**Comment by trentgrover-wf** [comment]
+1

**Comment by maxwellpeterson-wf** [comment]
+1

**Comment by evanweible-wf** [comment]
+1

**Comment by jayudey-wf** [comment]
QA Resource Approval: +1
- [x] Dev +1's only needed for Release ticket

Ready for merge and tag.

**Pull request merged**
